# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-13 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da categoria')),
                ('slug', models.SlugField(verbose_name='Atalho')),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome e Sobrenome do Editor')),
                ('facebooklink', models.CharField(blank=True, max_length=200, null=True, verbose_name='Link do Facebook pessoal')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('keywords', models.CharField(blank=True, help_text='Palavras chaves separadas por vírgula', max_length=150, null=True, verbose_name='Keywords')),
                ('capa', models.ImageField(default='static/img/logo.svg', upload_to='img/', verbose_name='Foto da capa')),
                ('nivel', models.PositiveSmallIntegerField(default=1, null=True)),
                ('text1', models.TextField()),
                ('picture1', models.ImageField(blank=True, upload_to='img/')),
                ('picturefigcaption1', models.CharField(default='Direitos reservados', max_length=200, verbose_name='Figcaption')),
                ('text2', models.TextField(blank=True)),
                ('picture2', models.ImageField(blank=True, upload_to='img/')),
                ('picturefigcaption2', models.CharField(default='Direitos reservados', max_length=200, verbose_name='Figcaption')),
                ('text3', models.TextField(blank=True)),
                ('picture3', models.ImageField(blank=True, upload_to='img/')),
                ('picturefigcaption3', models.CharField(default='Direitos reservados', max_length=200, verbose_name='Figcaption')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Categoria')),
                ('editor', models.ManyToManyField(to='blog.Editor')),
            ],
        ),
    ]
