# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-18 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160618_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='editor',
            new_name='Editor',
        ),
        migrations.AlterField(
            model_name='post',
            name='nivel',
            field=models.PositiveSmallIntegerField(default=1, null=True),
        ),
    ]
