# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-18 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160618_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Editores',
            new_name='Editor',
        ),
    ]
